[package]
name = "shreds"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.208"
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
