services:
  proxy:
    platform: linux/amd64
    image: jitolabs/jito-shredstream-proxy
    command: shredstream
    environment:
      - RUST_LOG=info
      - BLOCK_ENGINE_URL=https://amsterdam.mainnet.block-engine.jito.wtf
      - AUTH_KEYPAIR=auth.json
      - DESIRED_REGIONS=amsterdam
      - DEST_IP_PORTS=0.0.0.0:8001
    volumes:
      - ./auth.json:/app/auth.json
    network_mode: host

  shreds:
    image: piotrostr/shreds
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shreds
    command: ["./shreds", "--bind", "0.0.0.0:8001"]
    volumes:
      - type: bind
        source: ./raydium.json
        target: /raydium.json
      - .env:/.env
      - ./FAST.json:/FAST.json
      - ./shreds.log:/shreds.log
    ports:
      - "8001:8001/udp"

  bench:
    image: piotrostr/shreds
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bench
    volumes:
      - type: bind
        source: ./raydium.json
        target: /raydium.json
      - .env:/.env
      - ./FAST.json:/FAST.json
      - ./shreds.log:/shreds.log
    command: ["./shreds", "--benchmark"]
    ports:
      - "8001:8001/udp"
